eryajf/chatgpt-dingtalk

config.dev.json
config/config.go
gpt/gpt.go
main.go

- 修复配置文件中指定的超时时间不生效的问题。 #16 
- 一些其他问题的修复与优化

fix: timeout not work

---

go.mod
go.sum
gpt/gpt.go
main.go

feat: 添加接口请求的重试

---

README.md
docker-compose.yml

* 添加 docker compose 部署方式
* 更新部署文档

feat: 添加 docker compose 部署方式

---

docker-compose.yml

fix: 修复docker-compose的变量赋值问题

---

.github/workflows/TOC.yml
README.md
config.dev.json
config/config.go
docker-compose.yml
go.mod
go.sum
main.go
pkg/chatgpt/context.go
pkg/chatgpt/export.go
pkg/process/process_request.go
public/dingtalk.go
public/public.go

- `重磅：`支持了生成图片的能力。
- 改写发送钉钉消息的代码，支持发送Markdown消息。
- 废弃http包，使用ship包作为http框架。
- 优化readme展示。
close #110
close  #78
close  #53
close  #52

feat: 增加了生成图片的能力,以及其他一系列优化

---

config/config.go

fix: 修复配置指向的错误

---

main.go
pkg/ops/opstools.go
pkg/process/db.go
pkg/process/image.go
pkg/process/opstools.go
pkg/process/process_request.go
public/tools.go

feat: 增加域名以及证书信息的查询能力

---

README.md
config.example.yml
config/config.go
docker-compose.yml
main.go
pkg/logger/logger.go
pkg/process/process_request.go
public/chat.go
public/public.go
public/tools.go

feat: 添加对回调请求校验的能力,解决可被其他人调用的安全隐患

---

pkg/logger/logger.go

log_add_time

---

config/config.go
pkg/cache/user_chatid.go
pkg/cache/user_context.go

docs: 修复一些GPT的拼写错误

---

.github/workflows/docker-image.yml
README.md

fix: 修复docker镜像名称的取值问题

---

pkg/process/process_request.go

**在提出此拉取请求时，我确认了以下几点（请复选框）：**
钉钉支持Markdown语法有限，只是Markdown语法的一个子集，有部分用法可能无法渲染。但是这已经是目前最佳的选择了，改成Markdown后显示效果会相对好一些。
后续再看下如何优化Prompt相关配置提升整体的消息回复体验。
提交的代码同时修改了图片的帮助，提示图片将通过消息回复，避免让用户去看程序根目录的images目录而不知所措。
目前只有Markdown的代码块支持不好（目前只做了#的转义，如需copy Markdown的代码请使用手机操作。因这块要做转义需要考虑全部的Markdown语法以及还有其他各种编程语言语法。但是钉钉官方并没有说Markdown消息支持代码块及表格这些，**如有钉钉的人看到，麻烦修复一下这个bug**）：
手机端可正常copy

feat: 将回复消息格式修改为Markdown，支持代码块的展示（仅PC端支持），如返回消息是Markdown格式将直接渲染

---

pkg/chatgpt/chatgpt.go

fix: request time out

---

README.md

docs: README.md新增star历史

---

README.md
config.example.yml
config/config.go
docker-compose.yml
go.mod
go.sum
main.go
public/example_bot.go
public/example_event.go

feat: 添加stream模式的支持

---

pkg/chatgpt/context.go

fix: 带有 userId 参数时请求 azure 会导致 500 错误。

---

README.md
config.example.yml

doc: 调整密钥的配置说明信息

---

.github/workflows/docker-image.yml
README.md
docker-compose.yml

doc: 说明文档中更改镜像为阿里仓库,解决拉取镜像难的问题

---

pkg/chatgpt/chatgpt.go
pkg/dingbot/dingbot.go

fix: 修复升级go-openai版本之后azure不可用的问题

---

Makefile
config/config.go
main.go
pkg/cache/user_base.go
pkg/chatgpt/chatgpt.go
pkg/chatgpt/context.go
pkg/chatgpt/export.go
pkg/db/sqlite.go
pkg/dingbot/client.go
pkg/dingbot/client_test.go
pkg/process/image.go
pkg/process/process_request.go
public/public.go
public/tools_test.go
scripts/goimports-reviser.sh

```
make goimports
```
**在提出此拉取请求时，我确认了以下几点（请复选框）：**

feat: makefile support go sort imports

---

config/config.go
go.mod
go.sum
pkg/chatgpt/context.go

**在提出此拉取请求时，我确认了以下几点（请复选框）：**
**本次PR更新内容：**
1. 使用 golang.org/x/image 包处理 webp 图像
2. 修复 runmode 默认值

fix: 替换 webp 图像处理包 以及修复 runmode 默认值

---

config.example.yml

修改默认 session_timeout 值
